### ISSUE TITLE
[REQ] Website request: xvideos.com

### ISSUE THREAD

**Issue by Archer2011** [OhMyGuus/I-Dont-Care-About-Cookies#101]
**Website URL(s)**

- xvideos.com

**Browser**
[x ] Firefox
[] Chrome

**Extension version**
V1.0.4

**Comment by OhMyGuus** [comment]
Can't seem to find the cookie popup/warning.

**Comment by felixZmn** [comment]
Hey! 

One way to hide the popup would be executing the following line of code: 
`window.xv.disclaimer.setFeatures(false);`

Since I don't have any clue, how this extension is doing its magic (is there a short guide for beginners, where to start?), I unfortunately can't open a pull request, sorry :|

**Comment by OhMyGuus** [comment]
> Hey!
> 
> One way to hide the popup would be executing the following line of code: `window.xv.disclaimer.setFeatures(false);`
> 
> Since I don't have any clue, how this extension is doing its magic (is there a short guide for beginners, where to start?), I unfortunately can't open a pull request, sorry :|
> 
> Edit: Clearing your browser cookies or private mode could help if the popup is not shown. At least it helped me

Thanks for confirming that there is a cookie banner 😄 , apparently they show a different version if they detect a VPN so was a bit confused so thanks a lot. 
![image](https://user-images.githubusercontent.com/12090928/196002180-db0fb52b-4eda-4ca6-a310-5c3aee4d3af9.png)

**Comment by OhMyGuus** [comment]
Used my phone network and got it to work 👍 thanks for the help
