### ISSUE TITLE
Error installing addon on kiwi browser

### ISSUE THREAD

**Issue by dayt47** [OhMyGuus/I-Dont-Care-About-Cookies#82]
Hey, I got an error when trying to install the addon "I still don't care about cookies" on the kiwi browser on android via Chrome web store. 

![Screenshot_20221004-143720](https://user-images.githubusercontent.com/32074282/193953232-1326277e-d30f-49ef-acfc-1aa5a536317d.png)

**Comment by winskil** [comment]
The Chrome Web Store version still V1.0.0, which has some bugs. 
For now you can [download](https://github.com/OhMyGuus/I-Dont-Care-About-Cookies/releases/download/V1.0.3/IDCAC-chrome.zip) extension .zip and load it manually 
![Screenshot](https://user-images.githubusercontent.com/44670482/193954572-2f3cd02a-ff58-4b77-bb4f-5c0b4c3421a8.jpg)

**Comment by dayt47** [comment]
Yes I know, I have it installed it manually, but maybe the problem reoccurs with 1.0.3. Just wanted to inform the dev.

**Comment by OhMyGuus** [comment]
> Yes I know, I have it installed it manually, but maybe the problem reoccurs with 1.0.3. Just wanted to inform the dev.

Thanks for reporting it👍 It was indeed a bug that existed on v1.0.0 that I figured out after I uploaded it to chrome (Firefox gave an error while uploading it to the store, chrome didn't 😞 )
The new version is currently already a week in "review" on the chrome store which is a bit annoying.

**Comment by luetage** [comment]
@OhMyGuus My chrome extensions pass a review within 1 to 3 work days. I can only guess what the problem might be, but perhaps the name similarity with the original extensions is the problem. Google doesn’t care the original extension was bought by Avast and now there’s a “clone” of the extension with a very similar name, which in most other cases would hint at the developer trying to mislead people into downloading the clone instead of the real thing… I think bots do initial review  and this could be the reason why it’s taking so long. The positive review was stopped by an algorithm and now a human has to take a look at it, which takes far longer. But who knows…

**Comment by dayt47** [comment]
Thanks yes it works indeed! I didn't even had to disable and re-enable the addon. :)
